export function getProgramsBCIT() {
  return [
    "3D Modeling, Art & Animation",
    "Accounting",
    "Advanced Safety Management",
    "Agile Development",
    "Aircraft Gas Turbine Technician",
    "Aircraft Maintenance Engineer Category 'E' (Electronics)",
    "Aircraft Maintenance Engineer Category 'M' (Maintenance)",
    "Aircraft Maintenance Engineer Category 'S' (Structures)",
    "Airline and Flight Operations - Commercial Pilot - Fixed Wing",
    "Airline and Flight Operations - Commercial Pilot - Rotary Wing",
    "Applied Computer Information Systems (ACIS)",
    "Applied Computer Science (Database Option)",
    "Applied Computer Science (Games Development)",
    "Applied Computer Science (Human Computer Interface Option)",
    "Applied Computer Science (Network Security Applications Development Option)",
    "Applied Computer Science (Wireless and Mobile Applications Development Option)",
    "Applied Computing",
    "Applied Data Analytics",
    "Applied Database Administration and Design",
    "Applied Network Administration and Design",
    "Applied Software Development",
    "Applied Web Development",
    "Architectural Science",
    "Architectural and Building Technology",
    "Architectural and Structural CADD and Graphics Technician (Architectural Option)",
    "Architectural and Structural CADD and Graphics Technician (Structural Option)",
    "Artificial Intelligence Management",
    "Auto Body Repair and Refinishing Technician Foundation",
    "Automated Controls Installation and Maintenance",
    "Automotive Service Technician and Operations",
    "Automotive Technician (Honda/Acura Foundation)",
    "Automotive Technician (Toyota Foundation)",
    "Automotive Technician Foundation",
    "Aviation Management and Operations",
    "Bachelor of Creative Industries",
    "Bachelor of Health Science (Magnetic Resonance Imaging Option)",
    "Biomedical Engineering Technology",
    "Boilermaker Foundation",
    "Bridge Watch Rating",
    "Bridging Medical Radiography",
    "Broadcast and Digital Journalism",
    "Broadcast and Online Journalism",
    "Building Construction Technology",
    "Building Design and Architectural CAD",
    "Building Energy Modelling and Performance Analysis",
    "Building Engineering/Building Science",
    "Building Science",
    "Business Administration (General Option)",
    "Business Administration (Global Studies Option)",
    "Business Administration (Human Resources Option)",
    "Business Administration (Management Option)",
    "Business Administration (Marketing Option)",
    "Business Administration",
    "Business Analysis",
    "Business Analytics",
    "Business Data Management",
    "Business Fundamentals (BFUN)",
    "Business Information Technology Management",
    "Business Intelligence",
    "Business Management",
    "Business and Media Study Abroad",
    "CNC Machinist Technician",
    "Cabinetmaker (Joiner) Foundation",
    "Cardiac Sciences (Cardiac Rhythm Device Technology Option)",
    "Cardiac Sciences (Cardiovascular Technology Option)",
    "Cardiac Sciences (Electrophysiology Technology Option)",
    "Cardiology Technology",
    "Cardiovascular Perfusion",
    "Carpentry Framing and Forming Foundation",
    "Chemical and Environmental Engineering Technology",
    "Civil Engineering",
    "Civil Technology",
    "Clinical Genetics Technology",
    "Computer Aided Design (CAD) Technology",
    "Computer Information Systems Administration (CISA)",
    "Computer Information Technology (CIT)",
    "Computer Systems Technology (CST)",
    "Computer Systems",
    "Computerized Accounting",
    "Construction Drawings",
    "Construction Estimating",
    "Construction Management",
    "Construction Operations",
    "Construction Supervision",
    "Diagnostic Medical Sonography (General Sonography Option)",
    "Diagnostic Medical Sonography (General and Cardiac Sonography Option)",
    "Digital Communications and Wireless Technologies",
    "Digital Design and Development",
    "Digital Health",
    "Digital Marketing Foundations",
    "Digital Marketing Strategy",
    "Ecological Restoration",
    "Electrical Engineering",
    "Electrical Foundation",
    "Electrical and Computer Engineering Technology (ECET)",
    "Electroneurophysiology",
    "Electronics",
    "Environmental Public Health",
    "Event Marketing and Management Strategy",
    "Event Marketing and Planning Foundations",
    "Finance",
    "Financial Management (Finance Option)",
    "Financial Management (Financial Planning Option)",
    "Financial Management (Professional Accounting Option)",
    "Financial Planning",
    "Fire Executive Management",
    "Fire Protection Inspection and Testing",
    "Fish, Wildlife and Recreation",
    "Food Processing, Safety and Quality",
    "Food Safety",
    "Forensic Investigation (Crime and Intelligence Analysis Option)",
    "Forensic Investigation (Digital Forensics and Cybersecurity Option)",
    "Forensic Investigation (Forensic Science Option)",
    "Forest and Natural Areas Management",
    "Foundations in Occupational Health and Safety",
    "Front-End Web Developer (FWD)",
    "Full Stack Web Development (FSWD)",
    "General Insurance and Risk Management",
    "Geographic Information Systems",
    "Geomatics Engineering Technology",
    "Geomatics",
    "Global Business Studies",
    "Global Leadership",
    "Global Supply Chain Management",
    "Graphic Communications",
    "Graphic Design Foundations",
    "Graphic Design and Interactive Media",
    "Graphic Design",
    "Health Leadership",
    "Healthcare Unit Clerk",
    "Heating, Ventilation, Air Conditioning and Refrigeration Technician",
    "Heavy Duty Truck Technology",
    "Heavy Mechanical Trades Foundation",
    "Human Resource Management",
    "Industrial Instrumentation & Process Control Technician",
    "Industrial Network Cybersecurity",
    "Interior Design Fundamentals",
    "Interior Design",
    "International Trade and Transportation Logistics",
    "Ironworker Foundation",
    "Leadership",
    "Lean Six Sigma Principles",
    "Machinist Foundation",
    "Magnetic Resonance Imaging",
    "Marine Engineering",
    "Marine Mechanical Technical Foundation",
    "Marketing Management (Marketing Communications Option)",
    "Marketing Management (Professional Sales Option)",
    "Marketing Management - Customer Relationship Marketing",
    "Marketing Management - Entrepreneurship",
    "Marketing Management - Fundraising Management",
    "Marketing Management - Marketing Communications",
    "Marketing Management - Public Relations",
    "Marketing Management - Sales Skills",
    "Marketing Management",
    "Mechanical Engineering Technology",
    "Mechanical Engineering",
    "Mechanical Systems",
    "Mechatronics and Robotics",
    "Media Techniques and Marketing Communication",
    "Media Techniques for Business",
    "Medical Laboratory Science",
    "Medical Office Assistant",
    "Medical Radiography",
    "Metal Fabricator Foundation",
    "Millwright Foundation",
    "Mineral Exploration and Mining Technology",
    "Motorcycle Technician Foundation",
    "Music Business",
    "Nautical Sciences",
    "Network Administrator Technician",
    "New Media Design and Web Development",
    "Nonprofit Management",
    "Nuclear Medicine",
    "Nursing",
    "Occupational Health and Safety Practitioners",
    "Occupational Health and Safety",
    "Office Administrator with Technology (OAT)",
    "Operations Management (Facilities Management Option)",
    "Operations Management (Industrial Engineering Option)",
    "Operations Management (Management Engineering Option)",
    "Operations Management (Materials Management Option)",
    "Operations and Management Engineering",
    "Payroll Administration",
    "Payroll and Human Resources",
    "Piping Foundation",
    "Polytechnic Teaching",
    "Power Engineering (General Program)",
    "Power and Process Engineering",
    "Professional Accounting",
    "Project Management",
    "Prosthetics and Orthotics",
    "Quality and Process Management",
    "Radiation Therapy",
    "Radio Arts & Entertainment",
    "Radio Arts and Entertainment",
    "Railway Conductor and Operations",
    "Refrigeration and Air Conditioning Mechanic",
    "Renewable Energy Electrical Systems Installation & Maintenance",
    "Residential Interiors",
    "Security Systems Technician",
    "Sheet Metal Worker Foundation",
    "Smart Grid Systems and Technologies",
    "Software Systems Developer",
    "Sonography (Cardiac Option)",
    "Specialty Nursing",
    "Strategic Human Resources Management",
    "Sustainable Business Leadership",
    "Sustainable Business",
    "Technical Arts",
    "Technical Writing",
    "Technology Entry",
    "Technology Management",
    "Technology Support Professional (TSP)",
    "Technology Teacher Education",
    "Television and Video Production",
    "Tourism and Hospitality",
    "Trades Discovery General",
    "Trades Discovery for Women",
    "User Interface and User Experience Design",
    "Video Production and Editing",
    "Web and Mobile Application Development",
    "Welder Foundation",
    "Other...",
  ];
}
