export function getThemes() {
  return [
    {
      id: "white",
      color: "#fff",
      colorDark: "#d6d6d6",
      colorLight: "#969696",
      text: "#000",
      filterNorm: "invert(1) saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) hue-rotate(120deg) saturate(0)",
      borders: "#a7a7a7",
      whiteButtonFilter: "invert(1)",
    },
    {
      id: "black",
      displayColor: "#1e1e1e",
      color: "#1e1e1e",
      colorDark: "#000",
      colorLight: "#3a3a3a",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "saturate(0)",
      glow: "#fff",
      borders: "#a7a7a7",
    },
    {
      id: "red",
      color: "#ff0000",
      colorDark: "#d1001d",
      colorLight: "#ff3838",
      text: "#000",
      filterNorm: "",
      filter: "brightness(0)",
      mapFilter: "invert(1) hue-rotate(180deg) saturate(5)",
    },
    {
      id: "orange",
      color: "#ff9100",
      colorDark: "#c56f00",
      colorLight: "#ffa238",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(100%) hue-rotate(210deg)",
    },
    {
      id: "green",
      color: "#14f300",
      colorDark: "#13b60d",
      colorLight: "#38ff42",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(70%) hue-rotate(290deg)",
    },
    {
      id: "foam",
      color: "#00ffbf",
      colorDark: "#00b688",
      colorLight: "#4fffca",
      text: "#000",
      filterNorm: "invert(1) saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(50%) hue-rotate(340deg)",
    },
    {
      id: "cyan",
      color: "#00e1ff",
      colorDark: "#00b6cd",
      colorLight: "#6beeff",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(.7) hue-rotate(5deg)",
    },
    {
      id: "blue",
      color: "#0011ff",
      colorDark: "#000983",
      colorLight: "#3867ff",
      text: "#fff",
      filterNorm: "invert(1) saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      glow: "#fff",
      mapFilter: "hue-rotate(230deg)",
    },
    {
      id: "indigo",
      color: "#5526ff",
      colorDark: "#330fb6",
      colorLight: "#6d38ff",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "hue-rotate(260deg) saturate(75%)",
    },
    {
      id: "purple",
      color: "#ae00ff",
      colorDark: "#7c02b5",
      colorLight: "#c038ff",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "hue-rotate(285deg)",
    },
    {
      id: "pink",
      color: "#ff00f2",
      colorDark: "#db00c9",
      colorLight: "#ff56e3",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) hue-rotate(90deg) saturate(3)",
    },
  ];
}
