export function getThemes() {
  return [
    {
      id: "white",
      color: "#fff",
      colorDark: "#b9b9b9",
      text: "#000",
      filterNorm: "invert(1) saturate(0)",
      filter: "brightness(0)",
    },
    {
      id: "black",
      displayColor: "#1e1e1e",
      color: "#1e1e1e",
      colorDark: "#000",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
    },
    {
      id: "red",
      color: "#ff0000",
      colorDark: "#ad0000ff",
      text: "#000",
      filterNorm: "",
      filter: "brightness(0)",
    },
    {
      id: "orange",
      color: "#ff9100",
      colorDark: "#b36500ff",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
    },
    {
      id: "green",
      color: "#14f300ff",
      colorDark: "#13b60d",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
    },
    {
      id: "foam",
      color: "#00ffbf",
      colorDark: "#00b688",
      text: "#000",
      filterNorm: "invert(1) saturate(0)",
      filter: "brightness(0)",
    },
    {
      id: "cyan",
      color: "#00e1ff",
      colorDark: "#00b8be",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
    },
    {
      id: "blue",
      color: "#0011ff",
      colorDark: "#000983",
      text: "#fff",
      filterNorm: "invert(1) saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
    },
    {
      id: "indigo",
      color: "#5526ff",
      colorDark: "#330fb6",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
    },
    {
      id: "purple",
      color: "#ae00ff",
      colorDark: "#8a00ca",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
    },
    {
      id: "pink",
      color: "#ff00f2",
      colorDark: "#db00c9",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
    },
  ];
}
