export function getThemes() {
  return [
    {
      id: "white",
      color: "#fff",
      colorDark: "#d6d6d6",
      colorLight: "#969696",
      text: "#000",
      filterNorm: "invert(1) saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) hue-rotate(120deg) saturate(0)",
      borders: "#a7a7a7",
      whiteButtonFilter: "invert(1)",
    },
    {
      id: "black",
      displayColor: "#1e1e1e",
      color: "#1e1e1e",
      colorDark: "#000",
      colorLight: "#3a3a3a",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "saturate(0)",
      glow: "#fff",
      borders: "#a7a7a7",
    },
    {
      id: "red",
      color: "#ff0000",
      colorDark: "#a90000",
      colorLight: "#ff4e4e",
      text: "#fff",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "hue-rotate(0) brightness(1.15)",
    },
    {
      id: "orange",
      color: "#ff9100",
      colorDark: "#d77900",
      colorLight: "#ffa238",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(100%) hue-rotate(210deg)",
      whiteButtonFilter: "invert(1)",
      specialBG: "#ffbf6c",
    },
    {
      id: "green",
      color: "#14f300",
      colorDark: "#13b60d",
      colorLight: "#38ff42",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(70%) hue-rotate(290deg)",
      whiteButtonFilter: "invert(1)",
      specialBG: "#6bf558",
    },
    {
      id: "foam",
      color: "#00ffbf",
      colorDark: "#00b688",
      colorLight: "#4fffca",
      text: "#000",
      filterNorm: "invert(1) saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(50%) hue-rotate(340deg)",
      whiteButtonFilter: "invert(1)",
      specialBG: "#006d51",
    },
    {
      id: "cyan",
      color: "#00e1ff",
      colorDark: "#00bdf5",
      colorLight: "#6beeff",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) saturate(.7) hue-rotate(5deg)",
      whiteButtonFilter: "invert(1)",
      specialBG: "#bef7ff",
    },
    {
      id: "blue",
      color: "#0011ff",
      colorDark: "#000cad",
      colorLight: "#3867ff",
      text: "#fff",
      filterNorm: "invert(1) saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      glow: "#fff",
      mapFilter: "hue-rotate(230deg)",
      specialBG: "#000435",
    },
    {
      id: "indigo",
      color: "#5526ff",
      colorDark: "#330fb6",
      colorLight: "#6d38ff",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "hue-rotate(260deg) saturate(75%)",
      specialBG: "#29156f",
    },
    {
      id: "purple",
      color: "#ae00ff",
      colorDark: "#7c02b5",
      colorLight: "#c038ff",
      text: "#fff",
      filterNorm: "saturate(0)",
      filter: "invert(1) saturate(0) contrast(2)",
      mapFilter: "hue-rotate(285deg)",
      specialBG: "#3c005b",
    },
    {
      id: "pink",
      color: "#ff00f2",
      colorDark: "#e300b3",
      colorLight: "#ff56e3",
      text: "#000",
      filterNorm: "saturate(0)",
      filter: "brightness(0)",
      mapFilter: "invert(1) hue-rotate(90deg) saturate(3)",
      whiteButtonFilter: "invert(1)",
      specialBG: "#ffadfd",
    },
  ];
}
